version: '3.8'

services:
  backend:
    build: ./backend
    container_name: futbolmania_backend
    ports:
      - "3000:3000"
    volumes:
      # 🛡️ LA MAGIA DEL GUARDADO LOCAL:
      # Sincroniza la carpeta de tu PC con la del contenedor.
      # Así, cuando SQLite cree "foro.db", se guardará en tu disco duro real.
      - ./backend:/app
      # Evitamos sobrescribir los módulos de node locales
      - /app/node_modules
    environment:
      - NODE_ENV=development